// List of popular international airports
const airports = [
    { code: "ATL", name: "Hartsfield-Jackson Atlanta International Airport", city: "Atlanta", country: "USA" },
    { code: "PEK", name: "Beijing Capital International Airport", city: "Beijing", country: "China" },
    { code: "DXB", name: "Dubai International Airport", city: "Dubai", country: "UAE" },
    { code: "HND", name: "Tokyo Haneda Airport", city: "Tokyo", country: "Japan" },
    { code: "LAX", name: "Los Angeles International Airport", city: "Los Angeles", country: "USA" },
    { code: "LHR", name: "London Heathrow Airport", city: "London", country: "UK" },
    { code: "CDG", name: "Paris Charles de Gaulle Airport", city: "Paris", country: "France" },
    { code: "JFK", name: "John F. Kennedy International Airport", city: "New York", country: "USA" },
    { code: "AMS", name: "Amsterdam Schiphol Airport", city: "Amsterdam", country: "Netherlands" },
    { code: "FRA", name: "Frankfurt Airport", city: "Frankfurt", country: "Germany" },
    { code: "SIN", name: "Singapore Changi Airport", city: "Singapore", country: "Singapore" },
    { code: "ICN", name: "Seoul Incheon International Airport", city: "Seoul", country: "South Korea" },
    { code: "DEL", name: "Indira Gandhi International Airport", city: "Delhi", country: "India" },
    { code: "BOM", name: "Chhatrapati Shivaji Maharaj International Airport", city: "Mumbai", country: "India" },
    { code: "HKG", name: "Hong Kong International Airport", city: "Hong Kong", country: "China" },
    { code: "DFW", name: "Dallas/Fort Worth International Airport", city: "Dallas", country: "USA" },
    { code: "CAN", name: "Guangzhou Baiyun International Airport", city: "Guangzhou", country: "China" },
    { code: "IST", name: "Istanbul Airport", city: "Istanbul", country: "Turkey" },
    { code: "ORD", name: "O'Hare International Airport", city: "Chicago", country: "USA" },
    { code: "SYD", name: "Sydney Kingsford Smith Airport", city: "Sydney", country: "Australia" },
    { code: "MEL", name: "Melbourne Airport", city: "Melbourne", country: "Australia" },
    { code: "YYZ", name: "Toronto Pearson International Airport", city: "Toronto", country: "Canada" },
    { code: "BCN", name: "Barcelona–El Prat Airport", city: "Barcelona", country: "Spain" },
    { code: "MAD", name: "Madrid Barajas International Airport", city: "Madrid", country: "Spain" },
    { code: "MUC", name: "Munich Airport", city: "Munich", country: "Germany" },
    { code: "FCO", name: "Leonardo da Vinci–Fiumicino Airport", city: "Rome", country: "Italy" },
    { code: "SFO", name: "San Francisco International Airport", city: "San Francisco", country: "USA" },
    { code: "ZRH", name: "Zurich Airport", city: "Zurich", country: "Switzerland" },
    { code: "DUB", name: "Dublin Airport", city: "Dublin", country: "Ireland" },
    { code: "CPH", name: "Copenhagen Airport", city: "Copenhagen", country: "Denmark" },
    { code: "DOH", name: "Hamad International Airport", city: "Doha", country: "Qatar" },
    { code: "AKL", name: "Auckland Airport", city: "Auckland", country: "New Zealand" },
    { code: "VIE", name: "Vienna International Airport", city: "Vienna", country: "Austria" },
    { code: "BKK", name: "Suvarnabhumi Airport", city: "Bangkok", country: "Thailand" },
    { code: "JNB", name: "O. R. Tambo International Airport", city: "Johannesburg", country: "South Africa" },
    { code: "KUL", name: "Kuala Lumpur International Airport", city: "Kuala Lumpur", country: "Malaysia" },
    { code: "GRU", name: "São Paulo–Guarulhos International Airport", city: "São Paulo", country: "Brazil" },
    { code: "MEX", name: "Mexico City International Airport", city: "Mexico City", country: "Mexico" },
    { code: "MNL", name: "Ninoy Aquino International Airport", city: "Manila", country: "Philippines" },
    { code: "CGK", name: "Soekarno–Hatta International Airport", city: "Jakarta", country: "Indonesia" }
];

